.TH "C++ Matrix" 1 "2020-03-23" "Man Page" "Utility Commands"

.SH NAME
C++ Matrix \- The Matrix Reloaded in Terminals

.SH SYNOPSIS
.B cxxmatrix
[\fIOPTION\fR]... [[\-\-] \fIMESSAGE\fR...]

.SH DESCRIPTION
Show number falls, banners, the Matrix rains, Conway's Game of Life and the Mandelbrot set in terminals.
The purpose of this program is to test the performance of terminal emulators.

.SS MESSAGE
Add a message for '\fIbanner\fR' scene.  When no messages are specified, a
message "\fIC++ MATRIX\fR" will be used.

.SS OPTIONS

.TP
.B "\-\-help"
Show help.

.TP
.B \-\-
The rest arguments are processed as \fIMESSAGE\fR.

.TP
.B \-m, \-\-message=\fIMESSAGE
Add a message for '\fIbanner\fR' scene.

.TP
.B \-s, \-\-scene=\fISCENE
Add scenes.
Comma separated list of '\fInumber\fR', '\fIbanner\fR', '\fIrain\fR', '\fIconway\fR', '\fImandelbrot\fR', '\fIrain\-forever\fR' and '\fIloop\fR'.

.TP
.B \-c, \-\-color=\fICOLOR
Set color.
One of '\fIdefault\fR', '\fIblack\fR', '\fIred\fR', '\fIgreen\fR', '\fIyellow\fR', '\fIblue\fR', '\fImagenta\fR', '\fIcyan\fR', '\fIwhite\fR',
integer \fI0\fR\-\fI255\fR (256 index color), '\fI#RGB\fR', and '\fI#RRGGBB\fR'.

.TP
.B \-\-colorspace=\fICOLORSPACE
Set colorspace.
One of '\fIdefault\fR'/'\fIxterm-256\fR'/'\fI256\fR', '\fIansi-8\fR'/'\fI8\fR', '\fIaix-16\fR'/'\fI16\fR', '\fIxterm-88\fR'/'\fI88\fR', '\fIxterm-rgb\fR', '\fIiso-rgb\fR'/'\fIrgb\fR', '\fIiso-cmy\fR'/'\fIcmy\fR', '\fIiso-cmyk\fR'/'\fIcmyk\fR', or '\fIiso-index\fR'/'\fIindex\fR'.

.TP
.B \-\-frame\-rate=\fINUM
Set the frame rate per second.
A positive number less than or equal to \fI1000\fR.
The default is \fI25\fR.

.TP
.B \-\-error\-rate=\fINUM
Set the factor for the rate of character changes.
A non-negative number.
The default is \fI1.0\fR.

.TP
.B \-\-diffuse
Turn on the background-color effect (default).
.TP
.B \-\-no\-diffuse
Turn off the background-color effect.

.TP
.B \-\-twinkle
Turn on the twinkling effect (default).
.TP
.B \-\-no\-twinkle
Turn off the twinkling effect.

.TP
.B \-\-preserve\-background
Preserve terminal background.
.TP
.B \-\-no\-preserve\-background
Not preserve terminal background (default).

.TP
.B \-\-rain\-density=\fINUM
Set the factor for the density of rain drops.
A positive number.
The default is \fI1.0\fR.

.SS Keyboard

.TP
.B C\-c (SIGINT), q, Q
Quit

.TP
.B C\-z (SIGTSTP)
Suspend

.TP
.B C\-m, RET
Show menu

.SH AUTHOR
Written by Koichi Murase @akinomyoga <https://github.com/akinomyoga>.

.SS COPYRIGHT
Copyright (C) 2020 Koichi Murase @akinomyoga <myoga.murase@gmail.com>.

.SS LICENSE
The source code is provided with the MIT license.

.SS WEB PAGE
GitHub page <https://github.com/akinomyoga/cxxmatrix>.

.SS REPORTING BUGS
Create an issue at the GitHub page <https://github.com/akinomyoga/cxxmatrix/issues>.
